{% set name = "makeself" %}
{% set version = "2.4.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/megastep/makeself/archive/release-{{ version }}.tar.gz
  sha256: 3ca30c6b60a873cf0e44c0d47e9778a46ec0ca2ba8feffb1dd62a34cc2226395
  patches:
    - conda-prefix.patch

build:
  number: 0
  skip: true  # [win]

requirements:
  run:
    - tar
    - findutils
    - gzip
  # for md5sum, cksum, sha256sum
    - coreutils
  # enables --gpg-encrypt
    - gnupg
  # enables --ssl-encrypt
    - openssl
  # enables --pigz
    - pigz
  # enables --zstd
    - zstd
  # enables --bzip2
    - bzip2
  # enables --pbzip2
    - pbzip2
  # enables --xz
    - xz
  # enables --lzo
    - lzo
  # enables --lz4
    - lz4

about:
  home: https://github.com/megastep/makeself
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: COPYING
  summary: Make self-extractable archives on Unix
  description: |
    makeself.sh is a small shell script that generates a self-extractable
    compressed tar archive from a directory. The resulting file appears as a
    shell script (many of those have a .run suffix), and can be launched as is.
    The archive will then uncompress itself to a temporary directory and an
    optional arbitrary command will be executed (for example an installation
    script). This is pretty similar to archives generated with WinZip
    Self-Extractor in the Windows world. Makeself archives also include
    checksums for integrity self-validation (CRC and/or MD5/SHA256 checksums).
  doc_url: https://github.com/megastep/makeself
  dev_url: https://github.com/megastep/makeself

extra:
  recipe-maintainers:
    - saraedum
